name: Build Android APK (notes_vault)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 1) Если нет pubspec.yaml — создаём полноценный проект (android/, gradle и т.д.)
      #    Если pubspec есть, но нет android/ — добавляем платформу Android.
      - name: Ensure Flutter skeleton exists
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create --project-name notes_vault .
          elif [ ! -d android ]; then
            flutter create --platforms=android .
          fi

      # 2) Кладём main.dart в lib/ (если вдруг лежит в корне)
      - name: Place main.dart into lib
        run: |
          if [ -f main.dart ]; then
            mkdir -p lib
            cp -f main.dart lib/main.dart
          fi
          test -f lib/main.dart || (echo "❌ lib/main.dart missing"; exit 1)

      # 3) Получаем зависимости
      - name: Flutter pub get
        run: flutter pub get

      # 4) Сборка APK (debug для удобной установки)
      - name: Build debug APK
        run: flutter build apk --debug

      # 5) Публикуем артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
