name: Build Android APK (notes_vault)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter create project
        run: flutter create --project-name notes_vault .

      - name: Ensure our lib/main.dart exists
        run: test -f lib/main.dart || (echo "lib/main.dart missing"; exit 1)

      - name: Install dependencies
        run: |
          flutter pub add shared_preferences share_plus || true
          flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
