name: Build Android APK (notes_vault)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 1) Если проекта ещё нет (нет android/), создаём каркас
      - name: Create Flutter skeleton if missing
        run: |
          if [ ! -d "android" ]; then
            flutter create --project-name notes_vault .
          fi

      # 2) Убедимся, что наш lib/main.dart есть (или берём из корня)
      - name: Ensure lib/main.dart is in place
        run: |
          if [ ! -f lib/main.dart ] && [ -f main.dart ]; then
            mkdir -p lib
            cp -f main.dart lib/main.dart
          fi
          test -f lib/main.dart || (echo "lib/main.dart missing"; exit 1)

      # 3) Зависимости под наш код
      - name: Flutter pub get (+ensure deps)
        run: |
          flutter pub add shared_preferences share_plus || true
          flutter pub get

      # 4) Сборка APK
      - name: Build debug APK
        run: flutter build apk --debug

      # 5) Публикация артефакта
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
