name: Build Android APK (notes_vault)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Ensure Flutter project structure
        run: |
          if [ ! -f pubspec.yaml ]; then
            flutter create --project-name notes_vault .
          fi

      - name: Copy main.dart if in root
        run: |
          if [ -f main.dart ]; then
            mkdir -p lib
            cp -f main.dart lib/main.dart
          fi
          test -f lib/main.dart || (echo "❌ main.dart missing"; exit 1)

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
