name: Build Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "android/**"
      - ".github/workflows/android_apk.yml"

permissions:
  contents: read

concurrency:
  group: android-apk-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_CHANNEL: stable
  FLUTTER_VERSION: "3.35.5"   # можно сменить при необходимости
  JAVA_VERSION: "17"

jobs:
  debug-apk:
    name: Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure lib/main.dart exists
        run: |
          if [ ! -f "lib/main.dart" ]; then
            echo "::error::File lib/main.dart not found. Put your app code into lib/main.dart."
            exit 1
          fi

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }} (${{ env.FLUTTER_CHANNEL }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      # Опционально: кэш Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Fetch packages
        run: flutter pub get

      - name: Analyze (optional)
        run: flutter analyze
        continue-on-error: true

      - name: Build debug APK
        run: |
          flutter --version
          flutter clean
          flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

  # --------- РЕЛИЗ (опционально, со сборкой и подписью) ----------
  release-apk:
    name: Release APK (signed)
    runs-on: ubuntu-latest
    needs: debug-apk
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure lib/main.dart exists
        run: |
          if [ ! -f "lib/main.dart" ]; then
            echo "::error::File lib/main.dart not found. Put your app code into lib/main.dart."
            exit 1
          fi

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }} (${{ env.FLUTTER_CHANNEL }})
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Fetch packages
        run: flutter pub get

      # --- Подпись релиза (заполни секреты в Settings → Secrets and variables → Actions) ---
      # ANDROID_KEYSTORE_BASE64  – base64 от your_keystore.jks
      # ANDROID_KEYSTORE_PASSWORD – пароль keystore
      # ANDROID_KEY_ALIAS         – alias ключа
      # ANDROID_KEY_PASSWORD      – пароль ключа (может совпадать с keystore)
      - name: Prepare keystore (if provided)
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
          cat > android/key.properties <<'PROPS'
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=upload-keystore.jks
          PROPS

      - name: Build release APK
        run: |
          flutter clean
          flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
          if-no-files-found: error
